sudo: false
language: php
php:
  - 5.6
before_script:
  - composer install
script:
  - export BRANCH=$TRAVIS_BRANCH
  - if [ ${BRANCH} != "master" ]; then
      exit 0;
    fi
  - vendor/bin/phpdoc -d src/ -t phpdocs/
  - release.sh
  
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(awk -F "=" '/SDK_VERSION/ {print $2}' src/settings.ini)
  - export TIMESTAMP=$(date +"%Y%m%d%H%M%S")
  - git tag -a $GIT_TAG -m "Version for git tag $GIT_TAG."
  
deploy:
  provider: releases
  api_key: 4c:13:f0:ee:aa:9a:7c:04:75:49:29:2d:d2:91:c2:55
  file: Sdk-Ris-Php-$GIT_TAG-$TIMESTAMP.zip
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

notifications:
  email:
    recipients:
      - sanjeev1992jha@gmail.com


