sudo: false
language: php
php:
  - 5.6
before_script:
  - composer install
script:
  - export BRANCH=$TRAVIS_BRANCH
  - if [ ${BRANCH} != "master" ]; then
      exit 0;
    fi
  - vendor/bin/phpdoc -d src/ -t phpdocs/
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(awk -F "=" '/SDK_VERSION/ {print $2}' src/settings.ini)
  - export TIMESTAMP=$(date +"%Y%m%d%H%M%S")
  - git tag -a $GIT_TAG -m "Version for git tag $GIT_TAG."
deploy:
  provider: releases
  api_key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5MDA0MzEiLCJhdWQiOiJLb3VudC4xIiwiaWF0IjoxNTYzOTM4NjA2LCJzY3AiOnsia2EiOnRydWUsImtjIjp0cnVlLCJhcGkiOnRydWUsInJpcyI6dHJ1ZX19.WidWQkNcPeVRlBdu77cgsyQOSMRqzQHnzH3S70cnU38
  file: Sdk-Ris-Php-$GIT_TAG-$TIMESTAMP.zip
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
notifications:
  email:
    recipients:
      - sanjeev1992jha@gmail.com


